apiVersion: argoproj.io/v1alpha1
kind: ConfigManagementPlugin
metadata:
  name: cdk8s-python
spec:
  version: v1.0
  init:
    command: [pipenv]
    args: [update]
  generate:
    command: [cdk8s, synth]
    args: [--stdout]
  discover:
    fileName: "*.py"